# Generated by Django 5.1.1 on 2024-09-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_toko_delete_moodentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toko',
            new_name='TokoEntry',
        ),
    ]
