# Generated by Django 5.1.1 on 2024-10-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tokoentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokoentry',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
