# Generated by Django 5.1.1 on 2024-10-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tokoentry_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokoentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
