# Generated by Django 5.1.1 on 2024-10-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tokoentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokoentry',
            name='image',
        ),
        migrations.AddField(
            model_name='tokoentry',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
